package com.chenlh.distributedlock.mapper;

import com.chenlh.distributedlock.model.MethodLock;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MethodLockMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table METHOD_LOCK
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table METHOD_LOCK
	 * @mbg.generated
	 */
	int insert(MethodLock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table METHOD_LOCK
	 * @mbg.generated
	 */
	MethodLock selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table METHOD_LOCK
	 * @mbg.generated
	 */
	List<MethodLock> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table METHOD_LOCK
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MethodLock record);
}